-- DROP DATABASE IF EXISTS blog;
--
-- CREATE DATABASE blog;

-- DROP OWNED BY admin;
--
-- DROP USER IF EXISTS blog;
--
-- CREATE USER admin WITH PASSWORD 'password' SUPERUSER;

CREATE TABLE "user"
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    is_admin BOOLEAN
);

CREATE TABLE post
(
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(50),
    user_id    INTEGER,
    date       DATE,
    text       VARCHAR(50),
    comment_id INT REFERENCES comment (comment_id)

);

CREATE TABLE comment
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text      VARCHAR(50),
    date      DATE,
    user_id    INTEGER,
    comment_id    INTEGER
);



ALTER TABLE post
    ADD CONSTRAINT fk_post
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_comment
        FOREIGN KEY (user_id)
            REFERENCES "user" (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_comment
        FOREIGN KEY (comment_id)
            REFERENCES "user" (id);
